### ISSUE TITLE
How to use it with RouterContext ?

### ISSUE THREAD

**Issue by Dzale** [BernzSed/axios-push#1]
Hey there,

below is my server.js file. Any idea how to use this package so i can fetch initial data from API and render it on server side ? 

https://gist.github.com/Dzale/b8ae5171b31ac4b65ce96b8b24a05bb4

Best regards,
Nikola

**Comment by BernzSed** [comment]
Hi Nikola,

When using this module, you don't fetch your data from your API before the initial render; instead, this module uses a feature of HTTP/2 called "server push" to improve performance.

To use this module, you'll have to use [Node's `http2` module](https://nodejs.org/api/http2.html) instead of the `http` module. Unfortunately, express.js [isn't yet compatible](https://github.com/expressjs/express/pull/3390) with the `http2` module, so you'll probably have to use another framework instead (such as Koa or Hapi).

Here is an example that uses `koa` and `http2`: https://github.com/BernzSed/axios-push-koa-redux-example/blob/master/src/server.jsx#L28


Finally, you'll have to do something with the axios instance. Consider using a module like [react-axios](https://www.npmjs.com/package/react-axios):

```jsx
markup = renderToString(
  <AxiosProvider instance={axios}>
    <RouterContext {...renderProps}/>
  </AxiosProvider>
);
```
You could then use the high-order component `withAxios` in your child components.

Does this help?
